# Generated by Django 5.2.7 on 2026-03-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Level 1: Guest'), (2, 'Level 2: Employee'), (3, 'Level 4: Mid-Management'), (4, 'Level 4: Senior Executive'), (5, 'Level 5: OCP Board Member')], default=1),
        ),
    ]
