# Generated by Django 5.2.7 on 2026-03-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp', '0002_alter_user_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='seed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
