# Generated by Django 5.2.7 on 2026-03-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocp', '0003_alter_asset_seed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
    ]
