# Generated by Django 5.2.7 on 2026-03-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Level 1: Guest'), (2, 'Level 2: Employee'), (3, 'Level 3: Mid-Management'), (4, 'Level 4: Senior Executive'), (5, 'Level 5: OCP Board Member')], default=1),
        ),
    ]
